# Generated by Django 4.1.5 on 2023-01-06 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Item title')),
                ('description', models.TextField(verbose_name='Item description')),
                ('location', models.CharField(max_length=150, verbose_name='Location of Apartment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'ordering': ('-date', 'price'),
            },
        ),
        migrations.CreateModel(
            name='ApartmentPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_to_apartment', models.ImageField(upload_to='apps-pictures/%Y/%m/%d')),
                ('pictures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.apartment', verbose_name='Pictures')),
            ],
        ),
    ]
