# Generated by Django 4.1.5 on 2023-01-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='user_id',
            new_name='user',
        ),
    ]
