# Generated by Django 4.1.5 on 2023-01-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_user_id_apartment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentpicture',
            name='pictures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_pictures', to='booking.apartment', verbose_name='Pictures'),
        ),
    ]
