# Generated by Django 4.1.5 on 2023-01-07 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_apartment_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Available time')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.apartment')),
            ],
        ),
        migrations.AlterField(
            model_name='apartmentpicture',
            name='image_to_apartment',
            field=models.ImageField(upload_to='apps-pictures/%Y/%m/%d', verbose_name='Image for post'),
        ),
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.apartment')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.apartmentavailabletime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
