# Generated by Django 4.1.5 on 2023-01-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_apartmentavailabletime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentavailabletime',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='booking.apartment'),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_time', to='booking.apartment'),
        ),
    ]
